# Generated by Django 5.1.1 on 2024-09-19 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_vendor_email_remove_vendor_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock_quantity',
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.ImageField(upload_to='products/'),
        ),
    ]
