# Generated by Django 5.1.1 on 2024-09-23 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_review_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='customer',
            new_name='name',
        ),
    ]
