"""add job_descriptions

Revision ID: 07fead51181c
Revises: be20eb1ea3f7
Create Date: 2026-03-02 10:58:27.406848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07fead51181c'
down_revision = 'be20eb1ea3f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_descriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('company', sa.String(length=140), nullable=True),
    sa.Column('location', sa.String(length=140), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('analyzed', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_descriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_descriptions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_descriptions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_descriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_descriptions_user_id'))
        batch_op.drop_index(batch_op.f('ix_job_descriptions_created_at'))

    op.drop_table('job_descriptions')
    # ### end Alembic commands ###
