"""phase6_phase7

Revision ID: 6b6248f24786
Revises: 07fead51181c
Create Date: 2026-03-02 11:40:41.860820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b6248f24786'
down_revision = '07fead51181c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bulk_ranking_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('jd_id', sa.Integer(), nullable=False),
    sa.Column('jd_title', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('total_files', sa.Integer(), nullable=False),
    sa.Column('processed_files', sa.Integer(), nullable=False),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bulk_ranking_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bulk_ranking_runs_jd_id'), ['jd_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bulk_ranking_runs_user_id'), ['user_id'], unique=False)

    op.create_table('resume_profile_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('snapshot_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resume_profile_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resume_profile_versions_profile_id'), ['profile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_resume_profile_versions_user_id'), ['user_id'], unique=False)

    op.create_table('resume_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('profile_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resume_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resume_profiles_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resume_profiles_user_id'))

    op.drop_table('resume_profiles')
    with op.batch_alter_table('resume_profile_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resume_profile_versions_user_id'))
        batch_op.drop_index(batch_op.f('ix_resume_profile_versions_profile_id'))

    op.drop_table('resume_profile_versions')
    with op.batch_alter_table('bulk_ranking_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bulk_ranking_runs_user_id'))
        batch_op.drop_index(batch_op.f('ix_bulk_ranking_runs_jd_id'))

    op.drop_table('bulk_ranking_runs')
    # ### end Alembic commands ###
